In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
df = pd.read_excel("C:\\suyash_mishra\\IT_skills\\Infonexus_project\\superStore.xlsx")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Shipping Days,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,...,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,TotalSales,Dis_amt,Total
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,2,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,...,Samsung Convoy 3,221.98,2,0.0,62.15,40.77,High,443.96,0.00000,403.19000
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,2,Second Class,JR-162107,Justin Ritter,Corporate,NaN,...,"Novimex Executive Leather Armchair, Black",3709.40,9,0.1,-288.77,923.63,Critical,33384.60,33.38460,32427.58540
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,1,First Class,CR-127307,Craig Reiter,Consumer,NaN,...,"Nokia Smart Phone, with Caller ID",5175.17,9,0.1,919.97,915.49,Medium,46576.53,46.57653,45614.46347
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,2,First Class,KM-1637548,Katherine Murray,Home Office,NaN,...,"Motorola Smart Phone, Cordless",2892.51,5,0.1,-96.54,910.16,Medium,14462.55,14.46255,13537.92745
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,1,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,...,"Sharp Wireless Fax, High-Speed",2832.96,8,0.0,311.52,903.04,Critical,22663.68,0.00000,21760.64000

In [16]:
df["Order Date"] = pd.to_datetime(df["Order Date"], errors="coerce")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], errors="coerce")

In [18]:
top_products = df.groupby("Product Name", as_index=False)["Sales"].sum().sort_values("Sales", ascending=False).head(5)
(top_products)

                        Product Name     Sales
302  Motorola Smart Phone, Full Size  48542.52
118     Cisco Smart Phone, Full Size  41325.20
10      Apple Smart Phone, Full Size  39334.46
311     Nokia Smart Phone, Full Size  27661.97
373    Samsung Smart Phone, Cordless  25438.59

In [19]:
category_sales = df.groupby("Category", as_index=False)["Sales"].sum().sort_values("Sales", ascending=False)
(category_sales)

          Category      Sales
2       Technology  727083.13
0        Furniture  581071.86
1  Office Supplies  339031.48

In [20]:
region_profit = df.groupby("Region", as_index=False)["Profit"].sum().sort_values("Profit", ascending=False)
(region_profit)

               Region    Profit
15      Southern Asia  35549.07
6        Eastern Asia  35202.70
11            Oceania  32775.49
20     Western Europe  28454.44
10    Northern Europe  22868.45
3     Central America  20929.83
16    Southern Europe  20425.68
7      Eastern Europe  12228.45
13  Southeastern Asia  10561.80
2      Central Africa   9375.42
12      South America   7723.58
9        North Africa   6848.10
4          Central US   5659.56
19       Western Asia   5120.87
1           Caribbean   4963.64
14    Southern Africa   4876.32
5      Eastern Africa   4302.72
8          Eastern US   2166.15
21         Western US   2114.03
17        Southern US   1350.59
18     Western Africa   1278.17
0              Canada    199.44

In [22]:
num_cols = df.select_dtypes(include="number").columns
corr = df[num_cols].corr()
(corr.round(2))

,Row ID,Shipping Days,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost,TotalSales,Dis_amt,Total
Row ID,1.00,0.03,0.12,-0.12,-0.11,-0.02,0.00,-0.18,-0.09,-0.10,-0.09
Shipping Days,0.03,1.00,0.09,0.24,0.10,-0.08,0.15,-0.25,0.21,-0.01,0.22
Postal Code,0.12,0.09,1.00,-0.07,-0.12,0.08,-0.08,-0.03,-0.03,-0.05,-0.03
Sales,-0.12,0.24,-0.07,1.00,0.53,-0.16,0.52,0.56,0.89,0.21,0.89
Quantity,-0.11,0.10,-0.12,0.53,1.00,0.05,0.13,0.29,0.74,0.38,0.74
Discount,-0.02,-0.08,0.08,-0.16,0.05,1.00,-0.56,-0.12,-0.08,0.68,-0.08
Profit,0.00,0.15,-0.08,0.52,0.13,-0.56,1.00,0.25,0.46,-0.47,0.46
Shipping Cost,-0.18,-0.25,-0.03,0.56,0.29,-0.12,0.25,1.00,0.44,0.13,0.43
TotalSales,-0.09,0.21,-0.03,0.89,0.74,-0.08,0.46,0.44,1.00,0.30,1.00
Dis_amt,-0.10,-0.01,-0.05,0.21,0.38,0.68,-0.47,0.13,0.30,1.00,0.29
Total,-0.09,0.22,-0.03,0.89,0.74,-0.08,0.46,0.43,1.00,0.29,1.00

In [23]:
# chart1

monthly_sales = df.groupby("YearMonth", as_index=False)["Sales"].sum().sort_values("YearMonth")

plt.figure(figsize=(10,4))
sns.lineplot(data=monthly_sales, x="YearMonth", y="Sales", marker="o")
plt.xticks(rotation=45)
plt.title("Monthly Sales Trend")
plt.tight_layout()
plt.show()

KeyError: 'YearMonth'